### PR TITLE
39 tokenizer bugfix

### LINKED ISSUE #39: Bug Fix: Argument Tokenizer does not register first flag
`add -j test -n test -s test
----------------------------------------
Error: Missing flag: -j`

Fix tokenizer to add dummy flag before all other flags.

### PR DESCRIPTION
**Pull request by zexueteh**
- Fixed tokenizer
- New test class for AddCommandParser
- Additional JUnit tests for ArgumentTokenizer

### CODE REVIEW

File: src/main/java/seedu/duke/logic/parser/ApplicationParser.java [hunk 1]
```diff
@@ -17,7 +17,7 @@
 public class ApplicationParser {
 
     private static final Pattern BASIC_COMMAND_FORMAT = Pattern.compile(
-            "^(?<commandWord>\\S+)(?:\\s+(?<arguments>.+))?$");
+            "^(?<commandWord>\\S+)(?<arguments>.+)?$");
```
Comment (irfandeen) [inline src/main/java/seedu/duke/logic/parser/ApplicationParser.java:20]: Replace regex with split.

File: src/test/java/seedu/duke/logic/parser/ArgumentTokenizerTest.java [hunk 2]
```diff
@@ -14,6 +14,8 @@
 public class ArgumentTokenizerTest {
     private final Flag invalidFlag = new Flag("--i");
```
Comment (irfandeen) [inline src/test/java/seedu/duke/logic/parser/ArgumentTokenizerTest.java]: Constant variables should have static modifier.

File: src/test/java/seedu/duke/logic/parser/AddCommandParserTest.java [hunk 3]
```diff
@@ -0,0 +1,17 @@
...
+
+import org.junit.jupiter.api.Test;
+import seedu.duke.logic.commands.AddCommand;
+import seedu.duke.logic.parser.exceptions.ParseException;
+
+
+public class AddCommandParserTest {
+    private AddCommandParser parser = new AddCommandParser();
+
+    @Test
```
Comment (irfandeen) [inline src/test/java/seedu/duke/logic/parser/AddCommandParserTest.java:11]: Test needs both happy path and error path.

File: src/test/java/seedu/duke/logic/parser/AddCommandParserTest.java [hunk 4]
```diff
@@ -0,0 +1,17 @@
...
+    void parse_validArgs_returnsAddCommand() throws ParseException {
+        String userInput = "add -n Google -j Software Engineer -s Applied";
```
Comment (irfandeen) [inline src/test/java/seedu/duke/logic/parser/AddCommandParserTest.java:13]: Perhaps more than one possible valid add command could be tested.

File: src/test/java/seedu/duke/logic/parser/ArgumentTokenizerTest.java [hunk 5]
```diff
@@ -27,7 +29,19 @@ public void tokenize_oneArg_success() {
     }
 
     @Test
-    public void tokenize_multipleArgs_success() {
+    public void tokenize_threeArgs_success() {
+        String argString = " -n JP Morgan & Chase -j Risk Analyst Intern -s 0";
+        HashMap<Flag, List<String>> argMap = ArgumentTokenizer.tokenize(argString, nameFlag, jobTitleFlag, statusFlag);
+
+        System.out.println(argMap.toString());
```
Comment (irfandeen) [inline src/test/java/seedu/duke/logic/parser/ArgumentTokenizerTest.java]: Remove debug prints.

File: src/test/java/seedu/duke/logic/parser/AddCommandParserTest.java (hunk 3 above)
Comment (zexueteh) [reply src/test/java/seedu/duke/logic/parser/AddCommandParserTest.java:11]: To be addressed in #22

**Review by irfandeen — APPROVED** [review]
